services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-nodes-splitaudio
    ports:
      - "5678:5678"
    environment:
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_REINSTALL_MISSING_PACKAGES: "true"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
      N8N_CUSTOM_EXTENSIONS: /home/node/custom
      GENERIC_TIMEZONE: "America/Sao_Paulo"
    volumes:
      - n8n-data:/home/node/.n8n
      - ./:/home/node/custom/n8n-nodes-splitaudio
    restart: unless-stopped

volumes:
  n8n-data: {}


